version: '3.8'

services:
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"    
    networks:
      - coffee-network

  service2:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - INVENTORY_URL=http://inventory-service:8082      
    depends_on:
      - inventory-service
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge